package com.zorvyn.financedashboard.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import java.io.Serial;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ============================================================================
 * TRANSACTION ENTITY — Core Financial Record
 * ============================================================================
 *
 * This is the heart of the financial dashboard. Each row represents a single
 * financial event (income or expense) tied to a user account.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SOFT DELETE IMPLEMENTATION
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * We implement soft deletes using two Hibernate annotations:
 *
 *   @SQLDelete → Intercepts Hibernate's DELETE SQL and replaces it with an
 *                UPDATE that sets is_deleted = true. The application code
 *                calls repository.delete(entity) normally — the SQL rewrite
 *                is transparent.
 *
 *   @SQLRestriction → Appends "is_deleted = false" to every SELECT query
 *                     generated by Hibernate for this entity. Deleted records
 *                     become invisible to normal queries without any code
 *                     changes in repositories or services.
 *
 * Why soft deletes in a financial system?
 *   1. REGULATORY COMPLIANCE: Financial records often must be retained for
 *      7+ years. Physical deletion would violate SOX / GDPR requirements.
 *   2. AUDIT TRAILS: Soft-deleted records can be audited, restored, or
 *      referenced in historical reports.
 *   3. DATA INTEGRITY: Foreign keys referencing deleted transactions won't
 *      break (e.g., in future reporting or analytics modules).
 *   4. UNDO CAPABILITY: Users can recover accidentally deleted transactions.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * AUDIT LOGGING
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Beyond the inherited createdAt/updatedAt from BaseEntity, transactions
 * track WHO created and last modified them via createdByUserId and
 * lastModifiedByUserId. This gives us a complete audit trail:
 *   - WHAT changed (the record itself)
 *   - WHEN it changed (timestamps)
 *   - WHO changed it (user IDs)
 *
 * We store user IDs (not full User references) to avoid lazy-loading
 * issues and keep the entity lightweight. If you need the user details,
 * join in the service layer.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * MONEY HANDLING
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * The amount field uses BigDecimal (mapped to NUMERIC(19,4) in PostgreSQL).
 * This is CRITICAL for financial applications:
 *   - double/float use IEEE 754 binary floating-point, which CANNOT
 *     represent 0.1 exactly (it becomes 0.1000000000000000055511151...)
 *   - BigDecimal / NUMERIC use arbitrary-precision decimal arithmetic
 *   - Precision 19 supports values up to 999,999,999,999,999.9999
 *   - Scale 4 handles most currency subdivisions (e.g., stock prices
 *     in 1/10,000ths of a cent)
 */
@Entity
@Table(
    name = "transactions",
    indexes = {
        /*
         * Composite index on (user_id, transaction_date) optimizes the most
         * common query pattern: "show me MY transactions for a DATE RANGE".
         * PostgreSQL can use this index for:
         *   - WHERE user_id = ? AND transaction_date BETWEEN ? AND ?
         *   - WHERE user_id = ? (leftmost prefix)
         * But NOT for:
         *   - WHERE transaction_date = ? (missing leftmost column)
         */
        @Index(name = "idx_txn_user_date", columnList = "created_by_user_id, transaction_date"),

        /*
         * Index on category supports the dashboard's "category-wise totals"
         * endpoint. Without this, GROUP BY category would scan the full table.
         */
        @Index(name = "idx_txn_category", columnList = "category"),

        /*
         * Index on type (INCOME/EXPENSE) supports the income/expense
         * summary endpoints and dynamic filtering.
         */
        @Index(name = "idx_txn_type", columnList = "type"),

        /*
         * Partial index candidate: is_deleted. In PostgreSQL, we'd ideally
         * create a partial index "WHERE is_deleted = false" for maximum
         * efficiency, but JPA @Index doesn't support partial indexes.
         * We handle this in the Flyway migration instead.
         */
        @Index(name = "idx_txn_deleted", columnList = "is_deleted")
    }
)
// ============================================================================
// SOFT DELETE: Rewrite DELETE → UPDATE is_deleted = true
// ============================================================================
@SQLDelete(sql = "UPDATE transactions SET is_deleted = true, updated_at = NOW() WHERE id = ?")
// ============================================================================
// SOFT DELETE: Auto-filter all SELECT queries to exclude deleted records
// ============================================================================
@SQLRestriction("is_deleted = false")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Transaction extends BaseEntity {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Transaction amount in the system's base currency.
     *
     * Using BigDecimal (not Double) because financial calculations demand
     * exact decimal arithmetic. The classic example:
     *   0.1 + 0.2 = 0.30000000000000004 in IEEE 754 (double)
     *   0.1 + 0.2 = 0.3 in BigDecimal
     *
     * Column definition NUMERIC(19,4) gives us:
     *   - 15 digits before the decimal point
     *   - 4 digits after (handles sub-cent precision for FX)
     *   - Range: -999,999,999,999,999.9999 to +999,999,999,999,999.9999
     */
    @Column(name = "amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    /**
     * Transaction classification: INCOME or EXPENSE.
     * Stored as STRING (not ordinal) for database readability and
     * refactoring safety. See Role enum for the same rationale.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private TransactionType type;

    /**
     * Free-form category label (e.g., "Salary", "Groceries", "Utilities").
     *
     * We chose a simple VARCHAR over a Category entity/enum because:
     *   1. Categories vary wildly between organizations.
     *   2. Users should be able to create custom categories freely.
     *   3. The dashboard aggregates by category using GROUP BY, which
     *      works equally well on VARCHAR and FK columns.
     *
     * If we needed strict category validation, we'd introduce a
     * `categories` reference table with a FK constraint here.
     */
    @Column(name = "category", nullable = false, length = 100)
    private String category;

    /**
     * The business date of the transaction (not the DB insert timestamp).
     *
     * Using LocalDate (not LocalDateTime) because:
     *   1. Financial transactions are dated, not timestamped — you record
     *      "March 15th payroll", not "March 15th 14:32:07 payroll".
     *   2. Date-range filtering in Specifications is cleaner with dates.
     *   3. The creation timestamp (for audit) is in BaseEntity.createdAt.
     */
    @Column(name = "transaction_date", nullable = false)
    private LocalDate transactionDate;

    /**
     * Optional free-text notes for additional context.
     * Using TEXT type (no length limit) because notes can contain
     * detailed descriptions, reference numbers, or justifications.
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    // ========================================================================
    // AUDIT LOGGING FIELDS
    // ========================================================================

    /**
     * ID of the user who created this transaction.
     * This is a denormalized reference (Long, not @ManyToOne) to avoid:
     *   1. Lazy-loading exceptions in serialization contexts
     *   2. Circular reference issues in JSON responses
     *   3. Unnecessary JOINs when we only need the user ID for audit logs
     *
     * The actual User entity can be resolved in the service layer if needed.
     */
    @Column(name = "created_by_user_id")
    private Long createdByUserId;

    /**
     * ID of the user who last modified this transaction.
     * Updated by the service layer on every PUT/PATCH operation.
     */
    @Column(name = "last_modified_by_user_id")
    private Long lastModifiedByUserId;

    // ========================================================================
    // SOFT DELETE FLAG
    // ========================================================================

    /**
     * Soft delete marker. When true, the record is logically deleted.
     *
     * Default false via @Builder.Default + DDL default ensures new records
     * are always visible. The @SQLRestriction annotation on the entity
     * automatically excludes deleted records from all Hibernate queries.
     *
     * To query deleted records (e.g., for admin recovery), use native
     * queries that bypass Hibernate's filter.
     */
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;
}
