-- =============================================================================
-- V1__init.sql — Database Schema Initialisation
-- =============================================================================
-- Flyway Migration: Version 1
--
-- This script creates the foundational schema for the Finance Dashboard API.
-- It runs exactly ONCE on first application startup. Flyway tracks applied
-- migrations in the `flyway_schema_history` table and never re-runs them.
--
-- Schema Design Principles:
--   1. All monetary columns use NUMERIC(19,4) for exact decimal arithmetic
--   2. All tables have created_at/updated_at for audit compliance
--   3. Foreign keys use ON DELETE RESTRICT to prevent orphaned records
--   4. Indexes optimise the most common query patterns
--
-- Naming Conventions:
--   Tables:      plural snake_case (users, transactions)
--   Columns:     singular snake_case (full_name, transaction_date)
--   Constraints: prefix_table_column (uk_users_email, idx_txn_user_date)
--   Sequences:   table_id_seq (auto-generated by IDENTITY)
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- USERS TABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- Primary authentication and authorisation table.
--
-- Design Notes:
--   - email is the unique login identifier (not username)
--   - password stores BCrypt hashes (60 chars) with room for future algorithms
--   - role is a VARCHAR enum (VIEWER, ANALYST, ADMIN)
--   - is_active enables soft-disable without deleting the user record
--
-- Why GENERATED ALWAYS AS IDENTITY instead of SERIAL?
--   SERIAL is a legacy PostgreSQL shorthand that creates a sequence + DEFAULT.
--   GENERATED ALWAYS AS IDENTITY is the SQL standard (since SQL:2003) and
--   prevents manual ID insertion, ensuring sequence integrity.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- User profile
    full_name    VARCHAR(150)  NOT NULL,
    email        VARCHAR(255)  NOT NULL,
    password     VARCHAR(255)  NOT NULL,

    -- RBAC role: VIEWER | ANALYST | ADMIN
    -- Using VARCHAR (not PostgreSQL ENUM type) because:
    --   1. Adding new roles doesn't require ALTER TYPE migration
    --   2. CHECK constraint is easier to modify than ENUM types
    --   3. Hibernate maps Java enums to VARCHAR, not PG ENUM
    role         VARCHAR(20)   NOT NULL
                 CHECK (role IN ('VIEWER', 'ANALYST', 'ADMIN')),

    -- Account status flag
    is_active    BOOLEAN       NOT NULL DEFAULT TRUE,

    -- Audit timestamps (managed by JPA @CreatedDate / @LastModifiedDate)
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE,

    -- Unique constraint on email with explicit name for clear error messages
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- Index for login lookup performance (findByEmail)
-- This is critical: login happens on EVERY authentication attempt
CREATE INDEX idx_users_email ON users (email);

-- Index for admin user listing/filtering by role
CREATE INDEX idx_users_role ON users (role);

-- ─────────────────────────────────────────────────────────────────────────────
-- TRANSACTIONS TABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- Core financial records table. Each row represents a single income or
-- expense event.
--
-- Design Notes:
--   - amount uses NUMERIC(19,4) for exact decimal arithmetic (not FLOAT!)
--   - type is INCOME or EXPENSE (binary classification)
--   - is_deleted implements soft-delete (records are never physically deleted)
--   - created_by_user_id / last_modified_by_user_id form the audit trail
--
-- Soft Delete Implementation:
--   The application layer (Hibernate @SQLRestriction) appends
--   "WHERE is_deleted = false" to all SELECT queries automatically.
--   A partial index (WHERE is_deleted = false) on frequently filtered
--   columns ensures optimal performance for the common case.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE transactions (
    id                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Financial data
    -- NUMERIC(19,4): 15 integer digits + 4 decimal places
    -- Range: -999,999,999,999,999.9999 to +999,999,999,999,999.9999
    amount                   NUMERIC(19, 4) NOT NULL
                             CHECK (amount > 0),

    -- Transaction classification
    type                     VARCHAR(20)    NOT NULL
                             CHECK (type IN ('INCOME', 'EXPENSE')),

    -- User-defined category (free-form, normalised in application layer)
    category                 VARCHAR(100)   NOT NULL,

    -- Business date of the transaction (not the DB insert timestamp)
    transaction_date         DATE           NOT NULL,

    -- Optional description/notes
    notes                    TEXT,

    -- ─── Audit Trail ─────────────────────────────────────────────────
    -- WHO created and last modified this record.
    -- References users(id) but without a FK constraint because:
    --   1. We don't want CASCADE DELETE on users to delete transactions
    --   2. We want to preserve audit data even if the user is deleted
    --   3. Performance: FK constraints add overhead to every INSERT/UPDATE
    created_by_user_id       BIGINT,
    last_modified_by_user_id BIGINT,

    -- Audit timestamps (managed by JPA auditing)
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP WITH TIME ZONE,

    -- ─── Soft Delete ─────────────────────────────────────────────────
    is_deleted               BOOLEAN NOT NULL DEFAULT FALSE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────────────────────
-- Each index is designed for a specific query pattern used by the application.
-- ─────────────────────────────────────────────────────────────────────────────

-- Composite index: "my transactions in a date range" — the most common query
-- Leftmost prefix (created_by_user_id) also serves "my transactions" queries
CREATE INDEX idx_txn_user_date ON transactions (created_by_user_id, transaction_date);

-- Category index: powers the GROUP BY category dashboard query
CREATE INDEX idx_txn_category ON transactions (category);

-- Type index: powers the income/expense filter and SUM queries
CREATE INDEX idx_txn_type ON transactions (type);

-- Soft delete index: speeds up the WHERE is_deleted = false filter
-- This is a regular index; ideally we'd use a partial index:
--   CREATE INDEX idx_txn_active ON transactions (id) WHERE is_deleted = false;
-- But JPA's @Index doesn't support partial indexes. We create BOTH:
CREATE INDEX idx_txn_deleted ON transactions (is_deleted);

-- Partial index for active records — PostgreSQL-specific optimisation
-- This index is MUCH smaller than a full index because it only includes
-- rows where is_deleted = false (the common case — 95%+ of queries).
CREATE INDEX idx_txn_active ON transactions (id)
    WHERE is_deleted = false;

-- Composite partial index for dashboard aggregation queries
-- Covers: SUM(amount) WHERE type = ? AND is_deleted = false
CREATE INDEX idx_txn_type_amount_active ON transactions (type, amount)
    WHERE is_deleted = false;

-- ─────────────────────────────────────────────────────────────────────────────
-- COMMENTS
-- ─────────────────────────────────────────────────────────────────────────────
-- PostgreSQL table/column comments for documentation purposes.
-- These are visible in pgAdmin, DBeaver, and other database tools.
-- ─────────────────────────────────────────────────────────────────────────────
COMMENT ON TABLE users IS 'User accounts for authentication and RBAC';
COMMENT ON COLUMN users.role IS 'RBAC role: VIEWER (read-only), ANALYST (read-write), ADMIN (full access)';
COMMENT ON COLUMN users.is_active IS 'FALSE = account disabled, valid credentials rejected';

COMMENT ON TABLE transactions IS 'Financial transaction records with soft-delete support';
COMMENT ON COLUMN transactions.amount IS 'Transaction amount in base currency, NUMERIC(19,4) for exact arithmetic';
COMMENT ON COLUMN transactions.is_deleted IS 'Soft-delete flag: TRUE = logically deleted, excluded from queries';
COMMENT ON COLUMN transactions.created_by_user_id IS 'Audit: ID of user who created this record';
COMMENT ON COLUMN transactions.last_modified_by_user_id IS 'Audit: ID of user who last modified this record';
